// Generated by CoffeeScript 1.6.3
(function() {
  var detectProxy, portcheck;

  portcheck = require('portchecker');

  detectProxy = function(request_defaults, callback) {
    var e;
    if (request_defaults == null) {
      request_defaults = {};
    }
    try {
      return portcheck.isOpen(8888, "localhost", function(is_open) {
        if (is_open) {
          request_defaults.proxy = "http://localhost:8888";
        }
        return typeof callback === "function" ? callback(request_defaults) : void 0;
      });
    } catch (_error) {
      e = _error;
      return typeof callback === "function" ? callback(request_defaults) : void 0;
    }
  };

  module.exports = detectProxy;

}).call(this);
